# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e150074b72d222bc00d1548483131b59"
name = "boa-home-task-IB"
handle = "boa-home-task-ib"
application_url = "https://mesa-margin-pop-none.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-1dd97ce5.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,unauthenticated_read_customers,write_customers"

[auth]
redirect_urls = [
  "https://mesa-margin-pop-none.trycloudflare.com/auth/callback",
  "https://mesa-margin-pop-none.trycloudflare.com/auth/shopify/callback",
  "https://mesa-margin-pop-none.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://mesa-margin-pop-none.trycloudflare.com/api/import_cart"
subpath = "import_cart"
prefix = "apps"

[pos]
embedded = false
